### PR TITLE
Bluetooth rename tool demo, initial commit.

### PR DESCRIPTION
**Pull request by scheib**

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
In order to make Polymer elements work, I had to remove entirely the `bower_components` folder and run `$ bower install -F`. Otherwise I would get JS errors:

```
localhost/:33 GET http://localhost:8000/bower_components/paper-button/paper-button.html 404 (File not found)
localhost/:202 GET http://localhost:8000/bower_components/iron-range-behavior/iron-range-behavior.html 404 (File not found)
localhost/:202 GET http://localhost:8000/bower_components/iron-fit-behavior/iron-fit-behavior.html 404 (File not found)
```

Regarding the demo, could we check if the characteristic is writable before enabling input?
Something like below would work. WDYT?

``` js
          .then(value => {
            window.value = value;
            nameInput.value = new TextDecoder("utf-8").decode(value);
            if (window.deviceName.properties.write) {
              enableInput();
            } else {
              handleError('Device name is not writable');
            }
          }) 
```

**Comment by beaufortfrancois** [comment]
One nit: Can you add it to [`README.md`](https://github.com/WebBluetoothCG/demos#web-bluetooth-demos) and [`index.html`](https://github.com/WebBluetoothCG/demos/blob/gh-pages/index.html) files as well?

**Comment by beaufortfrancois** [comment]
(gentle ping @scheib)

**Comment by scheib** [comment]
Take another look.

**Comment by beaufortfrancois** [comment]
Perfect! I'll merge it and add updated origin trial token.

**Comment by beaufortfrancois** [comment]
Done in https://github.com/WebBluetoothCG/demos/pull/49

**Pull request merged**
